# playbook to deploy all services
- include: detect_cluster.yaml

# allow executing ansible on coreos cluster members
- name: Bootstrap coreos cluster members with python
  hosts: coreos_cluster
  gather_facts: False
  roles:
    - role: defunctzombie.coreos-bootstrap
